### ISSUE TITLE
[講者] 講者內容更新

### ISSUE THREAD

**Issue by htchien** [GDGTaipei/DevFest#10]
每項講者內容所需格式：
- 姓名
- 職稱
- 公司或組織名稱
- 公司或組織 logo
- 來自國家
- 大頭照 (檔案或連結)
- 個人簡介
- 個人完整介紹
- 個人專長
- 是否為 Google 技術專家 (可附上 Google 技術專家個人介紹頁連結)
- 是否為 Google 技術社群成員 (可附上該社群個人介紹頁連結)
- 個人 facebook, G+, LinkedIn, Twitter 社交帳號連結 (若願意提供的話)

以上內容須更新至 /data/speakers.json 檔案內。

**Comment by nobodyyu** [comment]
update

**Comment by htchien** [comment]
@nobodyyu where did you update? I don't see it....

**Comment by nobodyyu** [comment]
I canceled the pull request, I delivered my data to 威宏, sorry for bothering

2016-11-19 22:47 GMT+08:00 Ted Chien <notifications@github.com>:
