### ISSUE TITLE
[文字]"由業界專家們提供包含 Android、網頁與雲端等技術內容" 請增加 iOS

### ISSUE THREAD

**Issue by weihung** [GDGTaipei/DevFest#17]

**Comment by htchien** [comment]
目前議程裡面的講題有關 iOS 的只有如何移植 Firebase 專案到 iOS 平台上，並沒有針對 iOS 做深入的開發技術，個人認為應該不太適合加上 iOS。如果講題內容有講到 iOS 相關技術的話，或許才會比較適合加上 iOS。

不過還是感謝您的提議。
